# Generated by Django 5.1.7 on 2025-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('registro_ans', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20)),
                ('razao_social', models.TextField()),
                ('nome_fantasia', models.TextField(blank=True, null=True)),
                ('modalidade', models.CharField(max_length=100)),
                ('logradouro', models.TextField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('ddd', models.CharField(blank=True, max_length=5, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_eletronico', models.TextField(blank=True, null=True)),
                ('representante', models.TextField(blank=True, null=True)),
                ('cargo_representante', models.TextField(blank=True, null=True)),
                ('regiao_de_comercializacao', models.IntegerField(blank=True, null=True)),
                ('data_registro_ans', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operadoras',
            },
        ),
    ]
